permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
gems: ['jekyll-slim']

highlighter: 'pygments'
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

title : 一个好人
tagline: 在闹市中修行
author :
  name : Byronlee
  email : lbyronlee@gmail.com
  github : Byronlee
  twitter : ginchenorlee
  feedburner : Ginchenorlee

production_url : http://www.ginchenorlee.com

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : Byronlee
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  analytics :
    provider : baidu
  #  google :
  #      tracking_id : 'UA-123-12'
  #  getclicky :
  #    site_id :
  #  mixpanel :
  #      token : '_MIXPANEL_TOKEN_'
  #  piwik :
  #      baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
  #      idsite : '1'                   # the id of the site on Piwik


  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
